config/routes.rb
Rails.application.routes.draw do

  get '/home', to: 'accueile#home'

  get '/team', to: 'show#team'

  get '/contact', to: 'show#contact'

  get '/home/potin/:id', to: 'gossip#potin'

  get '/home/auteur/:id', to: 'gossip#auteur'
  #get '/home/:potin_id', to



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  	has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_many :users
  has_many :gossips
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  has_many :comments
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_many :comments
end

app/controllers/accueile_controller.rb
class AccueileController < ApplicationController
  def home
    @name = 1#params[:id]
    @user = User.find(@name)
    @gossip = Gossip.all





  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def potin
    @id = params[:id]
    @gossip = Gossip.find(@id)

  end
  def auteur
    @id = params[:id]
    @auteur = User.find(@id)
  end
end

app/controllers/show_controller.rb
class ShowController < ApplicationController
  def team
  end
  def contact
  end
end

app/helpers/aceul_helper.rb
module AceulHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/views/accueile/home.html.erb
<h1>The Gossip Project</h1>
<p>Bienvenue dans notre application <strong><%= @user.first_name %></strong></p>

<p>
<% @gossip.length.times do |i|%>
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= @gossip[i].title%></h5>
        <h6 class="card-text">par : <%= @gossip[i].user.first_name%></h6>
        <p class="card-text"> </p>
        <a href="/home/potin/<%=i+1%>" class="btn btn-primary">Go to Gossip</a>
      </div>
    </div>
<%end%>
</p>

app/views/gossip/auteur.html.erb
<h1>AUTEUR</h1>
<ul>
  <li><%= @auteur.first_name%> <%= @auteur.last_name%>
    <ul><li>age : <%= @auteur.age%> ans</li>
      <li>email : <%= @auteur.email%></li>
      <li>+info : <%= @auteur.description%></li>
    </ul>
  </li>
</ul>

app/views/gossip/potin.html.erb
<h1><%=@gossip.title%></h1>
<p>Contenue : <%=@gossip.content%></p>
<p>Cree le : <%=@gossip.created_at%></p>
<a href="/home/auteur/<%=@gossip.user.id%>">Son auteur</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">

      <a class="navbar-brand" href="/home">TheGossipProject</a>


      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Team", team_path, :class=>"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", contact_path, :class=>"nav-link"%>
          </li>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/show/contact.html.erb
<center>
<h1>Contacter nous : </h1>
<p>Email : hilal-w@live.com<br>adress: Konoha route 32</p>
</center>

app/views/show/team.html.erb
<center>
<h1>TEAM</h1>
<p>MEMBRE DU GROUPS</p>
</center>

<div id="center_div">
<div class = "team">
<pre>



****************************hilal*********************************
                    """""""""   """""""'"""
  </pre>
  </div>
 
</div>